// Catálogo de análisis del laboratorio, generado a partir de la lista oficial
// de exámenes (495 en total). Cuando exista backend, este archivo se reemplaza
// por la consulta a /servicios (o al catálogo real, con precios y disponibilidad).
export type ServiceCategorySlug =
  "perfiles" | "hormonas" | "bioquimica" | "hematologia" | "coagulacion" | "anticuerpos" | "infecciosas" | "parasitologia" | "cultivos" | "marcadores" | "vitaminas" | "orina_heces" | "liquidos" | "toxicologia" | "alergias" | "fertilidad" | "genetica" | "vacunas" | "imagenologia";

export const serviceCategories: { slug: ServiceCategorySlug; label: string }[] = [
  { slug: "imagenologia", label: "Imagenología con IA" },
  { slug: "perfiles", label: "Perfiles y chequeos" },
  { slug: "hormonas", label: "Hormonas y endocrinología" },
  { slug: "bioquimica", label: "Química clínica general" },
  { slug: "hematologia", label: "Hematología" },
  { slug: "coagulacion", label: "Coagulación" },
  { slug: "anticuerpos", label: "Anticuerpos e inmunología" },
  { slug: "infecciosas", label: "Enfermedades infecciosas y serología" },
  { slug: "parasitologia", label: "Parasitología y micología" },
  { slug: "cultivos", label: "Cultivos y microbiología" },
  { slug: "marcadores", label: "Marcadores tumorales" },
  { slug: "vitaminas", label: "Vitaminas y minerales" },
  { slug: "orina_heces", label: "Orina y heces" },
  { slug: "liquidos", label: "Líquidos corporales" },
  { slug: "toxicologia", label: "Toxicología y drogas" },
  { slug: "alergias", label: "Alergias" },
  { slug: "fertilidad", label: "Fertilidad y reproducción" },
  { slug: "genetica", label: "Genética y biología molecular" },
  { slug: "vacunas", label: "Vacunas" },
];

export type LabService = {
  id: string;
  name: string;
  category: ServiceCategorySlug;
  // Solo se usa para equipos/estudios que NO están disponibles en todas las
  // sedes (por ahora, el ecógrafo y el rayos X, que solo están en Peral).
  // Es el "id" de una sede real de src/config/sedes.ts. La mayoría de
  // análisis no tiene este campo porque se toman en cualquier sede.
  onlySedeId?: string;
};

// TODO(backend): reemplazar por fetch a la API real del laboratorio
// (incluirá precio, tiempo de entrega y disponibilidad por sede).
export const labServices: LabService[] = [
  // Nuevos equipos (no vienen del listado original de 495 exámenes; se
  // agregan aparte porque son equipos, no análisis de laboratorio clásicos).
  { id: "ecografia-con-inteligencia-artificial", name: "ECOGRAFÍA CON INTELIGENCIA ARTIFICIAL", category: "imagenologia", onlySedeId: "cercado-peral" },
  { id: "rayos-x-de-ultima-generacion", name: "RAYOS X DE ÚLTIMA GENERACIÓN", category: "imagenologia", onlySedeId: "cercado-peral" },
  { id: "17-hidroxiprogesterona-ser", name: "17 HIDROXIPROGESTERONA SER.", category: "hormonas" },
  { id: "acido-folico-vitamina-b9", name: "ACIDO FOLICO (VITAMINA B9)", category: "vitaminas" },
  { id: "acido-urico-orina-24-hrs", name: "ACIDO URICO (ORINA 24 HRS.)", category: "orina_heces" },
  { id: "acido-urico-orina-simple", name: "ACIDO URICO (ORINA SIMPLE)", category: "orina_heces" },
  { id: "acido-urico-de", name: "ACIDO URICO DE", category: "bioquimica" },
  { id: "acido-urico-serico", name: "ACIDO URICO SERICO", category: "bioquimica" },
  { id: "acidos-biliares", name: "ACIDOS BILIARES", category: "bioquimica" },
  { id: "acth-a-m", name: "ACTH (A.M.)", category: "hormonas" },
  { id: "acth-p-m", name: "ACTH (P.M.)", category: "hormonas" },
  { id: "ada-dren-toraxico", name: "ADA (DREN TORAXICO)", category: "liquidos" },
  { id: "ada-lcr", name: "ADA (LCR)", category: "liquidos" },
  { id: "ada-liq-abdominal", name: "ADA (LIQ. ABDOMINAL)", category: "liquidos" },
  { id: "ada-liq-ascitico", name: "ADA (LIQ. ASCITICO)", category: "liquidos" },
  { id: "ada-liq-lumbar", name: "ADA (LIQ. LUMBAR)", category: "liquidos" },
  { id: "ada-liq-pericardico", name: "ADA (LIQ. PERICARDICO)", category: "liquidos" },
  { id: "ada-liq-peritoneal", name: "ADA (LIQ. PERITONEAL)", category: "liquidos" },
  { id: "ada-liq-pleural", name: "ADA (LIQ. PLEURAL)", category: "liquidos" },
  { id: "ada-liq-sinovial", name: "ADA (LIQ. SINOVIAL)", category: "liquidos" },
  { id: "ada-liq-bronco-alveolar", name: "ADA (LIQ.BRONCO ALVEOLAR)", category: "liquidos" },
  { id: "ada-liquido-ascitico", name: "ADA (LIQUIDO ASCITICO)", category: "liquidos" },
  { id: "ada-liquido-quistico", name: "ADA (LIQUIDO QUISTICO)", category: "liquidos" },
  { id: "ada-sec-herida", name: "ADA (SEC. HERIDA)", category: "bioquimica" },
  { id: "ada-sec-mama", name: "ADA (SEC. MAMA)", category: "bioquimica" },
  { id: "ada-sec-toraxica", name: "ADA (SEC.TORAXICA)", category: "bioquimica" },
  { id: "ada-en", name: "ADA EN", category: "bioquimica" },
  { id: "ada-serico", name: "ADA SERICO", category: "bioquimica" },
  { id: "adenovirus", name: "ADENOVIRUS", category: "infecciosas" },
  { id: "albumina-de", name: "ALBUMINA DE", category: "bioquimica" },
  { id: "albumina-serica", name: "ALBUMINA SERICA", category: "bioquimica" },
  { id: "alcohol-cualitativo-saliva", name: "ALCOHOL CUALITATIVO (SALIVA)", category: "toxicologia" },
  { id: "alergia-panel-32-alergenos", name: "ALERGIA, PANEL 32 ALERGENOS", category: "alergias" },
  { id: "alfa-feto-proteina", name: "ALFA FETO PROTEINA", category: "marcadores" },
  { id: "alfa-feto-proteina-materna", name: "ALFA FETO PROTEINA MATERNA", category: "marcadores" },
  { id: "amilasa-de", name: "AMILASA DE", category: "bioquimica" },
  { id: "amilasa-serica", name: "AMILASA SERICA", category: "bioquimica" },
  { id: "anca-anti-neutrof-anca-c-anca-p", name: "ANCA (ANTI-NEUTROF) ANCA C, ANCA P", category: "anticuerpos" },
  { id: "androstenediona", name: "ANDROSTENEDIONA", category: "hormonas" },
  { id: "anfetamina-cualitativo", name: "ANFETAMINA CUALITATIVO", category: "toxicologia" },
  { id: "anti-ccp-igg-peptido-ciclico-citrulinado", name: "ANTI CCP IGG (PEPTIDO CICLICO CITRULINADO)", category: "anticuerpos" },
  { id: "anti-celula-parietal-gastrica-suero", name: "ANTI CELULA PARIETAL GASTRICA(SUERO)", category: "anticuerpos" },
  { id: "anti-rnp-sm", name: "ANTI RNP/SM", category: "anticuerpos" },
  { id: "anti-rnp-70", name: "ANTI RNP-70", category: "anticuerpos" },
  { id: "anti-tiroglobulina", name: "ANTI TIROGLOBULINA", category: "hormonas" },
  { id: "anti-tiroglobulina-liq-aspirado", name: "ANTI TIROGLOBULINA LIQ. ASPIRADO", category: "hormonas" },
  { id: "anti-tpo", name: "ANTI TPO", category: "anticuerpos" },
  { id: "anti-neutralizantes-sars-cov-2", name: "ANTI.NEUTRALIZANTES SARS-COV-2", category: "genetica" },
  { id: "antic-islote-pancreatico", name: "ANTIC. ISLOTE PANCREATICO", category: "bioquimica" },
  { id: "anticoagulante-lupico", name: "ANTICOAGULANTE LUPICO", category: "coagulacion" },
  { id: "anticuerpos-antitiroideos-anti-tiro-anti-tpo", name: "ANTICUERPOS ANTITIROIDEOS (ANTI TIRO, ANTI TPO)", category: "hormonas" },
  { id: "antiestreptolisina-o", name: "ANTIESTREPTOLISINA O", category: "anticuerpos" },
  { id: "antinucleares-especif-ana", name: "ANTINUCLEARES ESPECIF.(ANA)", category: "anticuerpos" },
  { id: "apolipoproteina-a1", name: "APOLIPOPROTEINA A1", category: "bioquimica" },
  { id: "apolipoproteina-b", name: "APOLIPOPROTEINA B", category: "bioquimica" },
  { id: "barbituricos-cualitativo", name: "BARBITURICOS CUALITATIVO", category: "toxicologia" },
  { id: "benedict", name: "BENEDICT", category: "bioquimica" },
  { id: "benzodiazepinas-cualitativo", name: "BENZODIAZEPINAS CUALITATIVO", category: "toxicologia" },
  { id: "beta-2-microglobulina", name: "BETA 2 MICROGLOBULINA", category: "bioquimica" },
  { id: "beta-2-microglobulina-en-liq-ascitico", name: "BETA 2 MICROGLOBULINA EN LIQ. ASCITICO", category: "liquidos" },
  { id: "beta-2-glicoproteina-1-ac-igg", name: "BETA-2 GLICOPROTEINA 1, AC. IGG", category: "anticuerpos" },
  { id: "bhcg-varones", name: "BHCG (VARONES)", category: "hormonas" },
  { id: "bicarbonato", name: "BICARBONATO", category: "bioquimica" },
  { id: "bilirrubina-serica", name: "BILIRRUBINA SERICA", category: "bioquimica" },
  { id: "bilirrubinas-de", name: "BILIRRUBINAS DE", category: "bioquimica" },
  { id: "bilirrubinas-totales-y-fraccionadas-bil-tot-bil-dir-bil-ind", name: "BILIRRUBINAS TOTALES Y FRACCIONADAS (BIL TOT, BIL.DIR, BIL.IND)", category: "bioquimica" },
  { id: "bk-1-orina-24h", name: "BK 1 (ORINA 24H)", category: "cultivos" },
  { id: "bk-2-orina-24h", name: "BK 2 (ORINA 24H)", category: "cultivos" },
  { id: "bk-4-orina-24h", name: "BK 4 (ORINA 24H)", category: "cultivos" },
  { id: "bk-5-orina-simple", name: "BK 5 (ORINA SIMPLE)", category: "cultivos" },
  { id: "bk-de", name: "BK DE", category: "cultivos" },
  { id: "bk-de-esputo", name: "BK DE ESPUTO", category: "cultivos" },
  { id: "bk-de-sec-gluteo", name: "BK DE SEC. GLUTEO", category: "cultivos" },
  { id: "bk-seriado-esputo-2-muestras", name: "BK SERIADO (ESPUTO) 2 MUESTRAS", category: "cultivos" },
  { id: "bk-seriado-esputo-3-muestras", name: "BK SERIADO (ESPUTO) 3 MUESTRAS", category: "cultivos" },
  { id: "bk-seriado-heces-3-muestras", name: "BK SERIADO (HECES) 3 MUESTRAS", category: "cultivos" },
  { id: "bk-seriado-herida-2-muestras", name: "BK SERIADO (HERIDA) 2 MUESTRAS", category: "cultivos" },
  { id: "bk-seriado-orina-24-hrs-10-muestras", name: "BK SERIADO (ORINA 24 HRS) 10 MUESTRAS", category: "cultivos" },
  { id: "bk-seriado-orina-24h-3-muestras", name: "BK SERIADO (ORINA 24H) 3 MUESTRAS", category: "cultivos" },
  { id: "bk-seriado-orina-simple", name: "BK SERIADO (ORINA SIMPLE)", category: "cultivos" },
  { id: "brucella-hudleson", name: "BRUCELLA (HUDLESON)", category: "infecciosas" },
  { id: "bun-ureico", name: "BUN UREICO", category: "bioquimica" },
  { id: "ca-125", name: "CA 125", category: "marcadores" },
  { id: "ca-15-3", name: "CA 15 3", category: "marcadores" },
  { id: "ca-19-9", name: "CA 19 9", category: "marcadores" },
  { id: "calcio-orina-al-azar", name: "CALCIO (ORINA AL AZAR)", category: "vitaminas" },
  { id: "calcio-orina-de-12-horas", name: "CALCIO (ORINA DE 12 HORAS)", category: "vitaminas" },
  { id: "calcio-orina-de-24-horas", name: "CALCIO (ORINA DE 24 HORAS)", category: "vitaminas" },
  { id: "calcio-ionico", name: "CALCIO IONICO", category: "vitaminas" },
  { id: "calcio-serico", name: "CALCIO SERICO", category: "vitaminas" },
  { id: "calcitonina", name: "CALCITONINA*", category: "bioquimica" },
  { id: "campylobacter-antigeno-fecal", name: "CAMPYLOBACTER ANTIGENO FECAL", category: "infecciosas" },
  { id: "capacitacion-espermatica", name: "CAPACITACION ESPERMATICA", category: "fertilidad" },
  { id: "cardiolipina-autoantic-igg", name: "CARDIOLIPINA, AUTOANTIC. IGG", category: "anticuerpos" },
  { id: "cardiolipina-autoantic-igm", name: "CARDIOLIPINA, AUTOANTIC. IGM", category: "anticuerpos" },
  { id: "cea-ag-carcino-embrionario", name: "CEA (AG. CARCINO EMBRIONARIO)", category: "marcadores" },
  { id: "cea-de", name: "CEA DE", category: "marcadores" },
  { id: "cea-serico", name: "CEA SERICO", category: "marcadores" },
  { id: "chlamydia-trachomatis-igg", name: "CHLAMYDIA TRACHOMATIS IGG", category: "anticuerpos" },
  { id: "chlamydia-trachomatis-igm", name: "CHLAMYDIA TRACHOMATIS IGM", category: "anticuerpos" },
  { id: "citograma-de", name: "CITOGRAMA DE", category: "bioquimica" },
  { id: "citomegalovirus-igg", name: "CITOMEGALOVIRUS IGG", category: "infecciosas" },
  { id: "citomegalovirus-igg-en-lcr", name: "CITOMEGALOVIRUS IGG EN LCR", category: "infecciosas" },
  { id: "citomegalovirus-igm", name: "CITOMEGALOVIRUS IGM", category: "infecciosas" },
  { id: "citomegalovirus-igm-en-lcr", name: "CITOMEGALOVIRUS IGM EN LCR", category: "infecciosas" },
  { id: "citoquimico-de", name: "CITOQUIMICO DE", category: "liquidos" },
  { id: "citoquimico-l-c-r", name: "CITOQUIMICO L.C.R", category: "liquidos" },
  { id: "citoquimico-liq-pleural", name: "CITOQUIMICO LIQ. PLEURAL", category: "liquidos" },
  { id: "cloro", name: "CLORO", category: "bioquimica" },
  { id: "cloro-orina-al-azar", name: "CLORO (ORINA AL AZAR)", category: "orina_heces" },
  { id: "cloro-orina-de-12-horas", name: "CLORO ORINA DE 12 HORAS", category: "orina_heces" },
  { id: "cloro-orina-de-24-horas", name: "CLORO ORINA DE 24 HORAS", category: "orina_heces" },
  { id: "clostrid-difficile-a-b-hec", name: "CLOSTRID. DIFFICILE A+B(HEC)", category: "infecciosas" },
  { id: "co2-en-sangre-arterial", name: "CO2 EN SANGRE ARTERIAL", category: "bioquimica" },
  { id: "co2-en-sangre-venosa", name: "CO2 EN SANGRE VENOSA", category: "bioquimica" },
  { id: "cocaina-cuantitativo", name: "COCAINA (CUANTITATIVO)", category: "toxicologia" },
  { id: "cocaina-cualitativo", name: "COCAINA CUALITATIVO", category: "toxicologia" },
  { id: "cociente-albumina-creatinina-en-orina-de-24horas", name: "COCIENTE ALBUMINA/CREATININA EN ORINA DE 24HORAS", category: "orina_heces" },
  { id: "cociente-albumina-creatinina-en-orina-simple", name: "COCIENTE ALBUMINA/CREATININA EN ORINA SIMPLE", category: "orina_heces" },
  { id: "colesterol", name: "COLESTEROL", category: "bioquimica" },
  { id: "colesterol-en-liq-pleural", name: "COLESTEROL EN LIQ. PLEURAL", category: "liquidos" },
  { id: "colesterol-hdl", name: "COLESTEROL HDL", category: "bioquimica" },
  { id: "colesterol-ldl", name: "COLESTEROL LDL", category: "bioquimica" },
  { id: "colesterol-serico", name: "COLESTEROL SERICO", category: "bioquimica" },
  { id: "coloracion-cutanea-leishmania", name: "COLORACION CUTANEA LEISHMANIA", category: "parasitologia" },
  { id: "coloracion-de-pneumocistis", name: "COLORACION DE PNEUMOCISTIS", category: "bioquimica" },
  { id: "coloracion-para-isospora", name: "COLORACION PARA ISOSPORA", category: "parasitologia" },
  { id: "complemento-c3", name: "COMPLEMENTO C3", category: "anticuerpos" },
  { id: "complemento-c4", name: "COMPLEMENTO C4", category: "anticuerpos" },
  { id: "constantes-corpusculares-hcm-chcm-vcm", name: "CONSTANTES CORPUSCULARES (HCM, CHCM, VCM)", category: "hematologia" },
  { id: "coprocultivo", name: "COPROCULTIVO", category: "cultivos" },
  { id: "coprofuncional", name: "COPROFUNCIONAL", category: "orina_heces" },
  { id: "coprofuncional-en-bolsa-colectora", name: "COPROFUNCIONAL EN BOLSA COLECTORA", category: "orina_heces" },
  { id: "cortisol-12-pm", name: "CORTISOL 12 PM", category: "hormonas" },
  { id: "cortisol-30-minutos-post-medicacion", name: "CORTISOL 30 MINUTOS POST MEDICACION", category: "hormonas" },
  { id: "cortisol-60-minutos-post-medicacion", name: "CORTISOL 60 MINUTOS POST MEDICACION", category: "hormonas" },
  { id: "cortisol-am", name: "CORTISOL AM", category: "hormonas" },
  { id: "cortisol-pm", name: "CORTISOL PM", category: "hormonas" },
  { id: "cortisol-post-acth-0-25-mg-d", name: "CORTISOL POST ACTH 0.25 MG D", category: "hormonas" },
  { id: "cpk", name: "CPK", category: "bioquimica" },
  { id: "cpk-mb-stat", name: "CPK MB STAT", category: "bioquimica" },
  { id: "creatinina-orina-al-azar", name: "CREATININA (ORINA AL AZAR)", category: "orina_heces" },
  { id: "creatinina-sangre", name: "CREATININA (SANGRE)", category: "bioquimica" },
  { id: "creatinina-en-liq-peritoneal", name: "CREATININA EN LIQ. PERITONEAL", category: "liquidos" },
  { id: "creatinina-en-liquido-ascitico", name: "CREATININA EN LIQUIDO ASCITICO", category: "liquidos" },
  { id: "creatinina-en-orina-12hrs", name: "CREATININA EN ORINA 12HRS", category: "orina_heces" },
  { id: "creatinina-orina-de-24-hrs", name: "CREATININA ORINA DE 24 HRS", category: "orina_heces" },
  { id: "creatinina-post-dialisis", name: "CREATININA POST DIALISIS", category: "bioquimica" },
  { id: "creatinina-post-hidratacion", name: "CREATININA POST HIDRATACION", category: "bioquimica" },
  { id: "crioaglutininas", name: "CRIOAGLUTININAS", category: "anticuerpos" },
  { id: "crioglobulinas", name: "CRIOGLOBULINAS", category: "anticuerpos" },
  { id: "criptosporidium", name: "CRIPTOSPORIDIUM", category: "parasitologia" },
  { id: "cuerpos-cetonicos-en-orina", name: "CUERPOS CETONICOS EN ORINA", category: "orina_heces" },
  { id: "cuerpos-cetonicos-en-sangre", name: "CUERPOS CETONICOS EN SANGRE", category: "bioquimica" },
  { id: "cultivo-de", name: "CULTIVO DE", category: "cultivos" },
  { id: "cultivo-de-aspirado-bronquial", name: "CULTIVO DE ASPIRADO BRONQUIAL", category: "cultivos" },
  { id: "cultivo-de-bk-en-esputo", name: "CULTIVO DE BK EN ESPUTO", category: "cultivos" },
  { id: "cultivo-de-herida", name: "CULTIVO DE HERIDA", category: "cultivos" },
  { id: "cultivo-de-hongos-cuero-cabelludo", name: "CULTIVO DE HONGOS CUERO CABELLUDO", category: "parasitologia" },
  { id: "cultivo-de-impronta-de-manos", name: "CULTIVO DE IMPRONTA DE MANOS", category: "cultivos" },
  { id: "cultivo-de-liq-pleural", name: "CULTIVO DE LIQ. PLEURAL", category: "cultivos" },
  { id: "cultivo-de-liq-sinovial", name: "CULTIVO DE LIQ. SINOVIAL", category: "cultivos" },
  { id: "cultivo-de-sec-de-herida", name: "CULTIVO DE SEC. DE HERIDA", category: "cultivos" },
  { id: "cultivo-de-sec-nasal", name: "CULTIVO DE SEC. NASAL", category: "cultivos" },
  { id: "cultivo-de-sec-vaginal", name: "CULTIVO DE SEC. VAGINAL", category: "cultivos" },
  { id: "cultivo-de-sec-faringea", name: "CULTIVO DE SEC.FARINGEA", category: "cultivos" },
  { id: "cultivo-de-semen", name: "CULTIVO DE SEMEN", category: "cultivos" },
  { id: "cultivo-en-esputo", name: "CULTIVO EN ESPUTO", category: "cultivos" },
  { id: "cultivo-oseo-de-fractura", name: "CULTIVO OSEO DE FRACTURA", category: "cultivos" },
  { id: "cyfra-21-1-pulmon", name: "CYFRA 21-1 (PULMÓN)", category: "marcadores" },
  { id: "demodex-de", name: "DEMODEX DE", category: "parasitologia" },
  { id: "demodex-examen-directo", name: "DEMODEX, EXAMEN DIRECTO", category: "parasitologia" },
  { id: "densidad-en-liquido-peritoneal", name: "DENSIDAD EN LÍQUIDO PERITONEAL", category: "liquidos" },
  { id: "depuracion-de-creat-corregida", name: "DEPURACION DE CREAT. CORREGIDA", category: "bioquimica" },
  { id: "depuracion-de-creatinina-en-12h", name: "DEPURACION DE CREATININA EN 12H", category: "bioquimica" },
  { id: "depuracion-de-creatinina-en-24h", name: "DEPURACION DE CREATININA EN 24H", category: "bioquimica" },
  { id: "deteccion-leishmania-en-piel", name: "DETECCION LEISHMANIA EN PIEL", category: "parasitologia" },
  { id: "dhea-s", name: "DHEA-S", category: "hormonas" },
  { id: "dhl-de", name: "DHL DE", category: "bioquimica" },
  { id: "dhl-serico-deshidrogenasa-lactica", name: "DHL SERICO (DESHIDROGENASA LACTICA)", category: "bioquimica" },
  { id: "diferenciacion-celular-heces-eos-monon-polim", name: "DIFERENCIACION CELULAR HECES: (EOS, MONON, POLIM)", category: "orina_heces" },
  { id: "dimero-d", name: "DIMERO D", category: "coagulacion" },
  { id: "dna-ds-nativo-anticuerpos", name: "DNA DS (NATIVO), ANTICUERPOS", category: "anticuerpos" },
  { id: "drogas-panel-para-10-test-morf-barbit-fencic-thc-metanf-metad-antid-benzod-coc-anfet", name: "DROGAS PANEL PARA 10 TEST (MORF, BARBIT, FENCIC, THC, METANF, METAD, ANTID, BENZOD, COC, ANFET)", category: "toxicologia" },
  { id: "drogas-panel-para-2-test-coc-thc", name: "DROGAS PANEL PARA 2 TEST(COC-THC)", category: "toxicologia" },
  { id: "drogas-panel-para-5-test-benzod-coc-anfet-thc-metanf", name: "DROGAS PANEL PARA 5 TEST (BENZOD, COC, ANFET, THC, METANF)", category: "toxicologia" },
  { id: "electrolitos-en-orina-12-hrs-sodio-potasio-cloro-en-or-12h", name: "ELECTROLITOS EN ORINA 12 HRS. (SODIO, POTASIO, CLORO EN OR. 12H)", category: "orina_heces" },
  { id: "electrolitos-en-orina-24-hrs-sodio-potasio-cloro-en-or-24h", name: "ELECTROLITOS EN ORINA 24 HRS.(SODIO, POTASIO, CLORO EN OR. 24H)", category: "orina_heces" },
  { id: "electrolitos-orina-simple-sodio-potasio-cloro-en-o-simple", name: "ELECTROLITOS ORINA SIMPLE (SODIO, POTASIO, CLORO EN O.SIMPLE)", category: "orina_heces" },
  { id: "electrolitos-suero-sodio-potasio-cloro", name: "ELECTROLITOS SUERO (SODIO, POTASIO, CLORO)", category: "bioquimica" },
  { id: "eosinofilos-de-sec-nasal", name: "EOSINOFILOS DE SEC. NASAL", category: "hematologia" },
  { id: "eosinofilos-de-sec-nasofaringea", name: "EOSINOFILOS DE SEC. NASOFARINGEA", category: "hematologia" },
  { id: "eosinofilos-en", name: "EOSINOFILOS EN", category: "hematologia" },
  { id: "eosinofilos-serico", name: "EOSINOFILOS SERICO", category: "hematologia" },
  { id: "espermatograma", name: "ESPERMATOGRAMA", category: "fertilidad" },
  { id: "esputo-pneumocystis-jiroveci-carinii", name: "ESPUTO PNEUMOCYSTIS JIROVECI (CARINII)", category: "parasitologia" },
  { id: "estradiol", name: "ESTRADIOL", category: "hormonas" },
  { id: "estudio-de-calculo", name: "ESTUDIO DE CALCULO", category: "bioquimica" },
  { id: "examen-completo-de-orina", name: "EXAMEN COMPLETO DE ORINA", category: "orina_heces" },
  { id: "examen-completo-orina-condicional", name: "EXAMEN COMPLETO ORINA/CONDICIONAL", category: "orina_heces" },
  { id: "examen-directo", name: "EXAMEN DIRECTO", category: "bioquimica" },
  { id: "examen-directo-de", name: "EXAMEN DIRECTO DE", category: "bioquimica" },
  { id: "examen-directo-liq-pleural", name: "EXAMEN DIRECTO LIQ. PLEURAL", category: "liquidos" },
  { id: "extasis-cualitativo", name: "EXTASIS CUALITATIVO", category: "toxicologia" },
  { id: "extraccion-sanguinea", name: "EXTRACCION SANGUINEA", category: "bioquimica" },
  { id: "factor-reumatoideo", name: "FACTOR REUMATOIDEO", category: "anticuerpos" },
  { id: "fenciclidina-cualitativo", name: "FENCICLIDINA CUALITATIVO", category: "toxicologia" },
  { id: "fenomeno-le-serico", name: "FENOMENO LE SERICO", category: "anticuerpos" },
  { id: "ferritina-serica", name: "FERRITINA SERICA", category: "vitaminas" },
  { id: "fibrinogeno", name: "FIBRINOGENO", category: "coagulacion" },
  { id: "fosfatasa-alcalina", name: "FOSFATASA ALCALINA", category: "bioquimica" },
  { id: "fosforo", name: "FOSFORO", category: "vitaminas" },
  { id: "fosforo-en-orina-de-12-hrs", name: "FOSFORO EN ORINA DE 12 HRS", category: "vitaminas" },
  { id: "fosforo-en-orina-de-24-hrs", name: "FOSFORO EN ORINA DE 24 HRS", category: "vitaminas" },
  { id: "fosforo-orina-al-azar", name: "FOSFORO ORINA AL AZAR", category: "vitaminas" },
  { id: "fraccion-beta-bhcg-sangre", name: "FRACCION BETA BHCG(SANGRE)", category: "hormonas" },
  { id: "fragilidad-capilar", name: "FRAGILIDAD CAPILAR", category: "coagulacion" },
  { id: "frotis-de-tzanck", name: "FROTIS DE TZANCK", category: "bioquimica" },
  { id: "fsh", name: "FSH", category: "hormonas" },
  { id: "gases-arteriales", name: "GASES ARTERIALES", category: "bioquimica" },
  { id: "gases-arteriales-y-electrolitos", name: "GASES ARTERIALES Y ELECTROLITOS", category: "bioquimica" },
  { id: "gases-en-sangre-capilar", name: "GASES EN SANGRE CAPILAR", category: "bioquimica" },
  { id: "gases-en-sangre-venosa", name: "GASES EN SANGRE VENOSA", category: "bioquimica" },
  { id: "gases-en-sangre-venosa-y-electrolitos", name: "GASES EN SANGRE VENOSA Y ELECTROLITOS", category: "bioquimica" },
  { id: "ggtp-gamma-glutamil-transp", name: "GGTP (GAMMA GLUTAMIL TRANSP.)", category: "bioquimica" },
  { id: "glucosa-120-min", name: "GLUCOSA 120 MIN", category: "bioquimica" },
  { id: "glucosa-150-min", name: "GLUCOSA 150 MIN", category: "bioquimica" },
  { id: "glucosa-180-min", name: "GLUCOSA 180 MIN", category: "bioquimica" },
  { id: "glucosa-240-min", name: "GLUCOSA 240 MIN", category: "bioquimica" },
  { id: "glucosa-30-min", name: "GLUCOSA 30 MIN", category: "bioquimica" },
  { id: "glucosa-300-min", name: "GLUCOSA 300 MIN", category: "bioquimica" },
  { id: "glucosa-60-min", name: "GLUCOSA 60 MIN", category: "bioquimica" },
  { id: "glucosa-90-min", name: "GLUCOSA 90 MIN", category: "bioquimica" },
  { id: "glucosa-basal-glicemia", name: "GLUCOSA BASAL (GLICEMIA)", category: "bioquimica" },
  { id: "glucosa-basal-y-post-prandial", name: "GLUCOSA BASAL Y POST PRANDIAL", category: "bioquimica" },
  { id: "glucosa-post-prandial", name: "GLUCOSA POST PRANDIAL", category: "bioquimica" },
  { id: "gonadotrofina-corionica-orina-sangre", name: "GONADOTROFINA CORIONICA(ORINA/SANGRE)", category: "orina_heces" },
  { id: "gota-gruesa", name: "GOTA GRUESA", category: "parasitologia" },
  { id: "gota-gruesa-de-herida", name: "GOTA GRUESA DE HERIDA", category: "parasitologia" },
  { id: "gram-abceso-de-pie", name: "GRAM ABCESO DE PIE", category: "cultivos" },
  { id: "gram-de", name: "GRAM DE", category: "cultivos" },
  { id: "gram-de-contenido-vesicular", name: "GRAM DE CONTENIDO VESICULAR", category: "cultivos" },
  { id: "gram-de-liquido-pleural", name: "GRAM DE LIQUIDO PLEURAL:", category: "cultivos" },
  { id: "gram-de-sec-cuello-uterino", name: "GRAM DE SEC. CUELLO UTERINO", category: "cultivos" },
  { id: "gram-de-sec-faringea", name: "GRAM DE SEC. FARINGEA:", category: "cultivos" },
  { id: "gram-de-sec-nasal", name: "GRAM DE SEC. NASAL", category: "cultivos" },
  { id: "gram-de-sec-nasofaringea", name: "GRAM DE SEC. NASOFARINGEA:", category: "cultivos" },
  { id: "grasa-neutra-sudan-iii", name: "GRASA NEUTRA (SUDAN III)", category: "bioquimica" },
  { id: "grupo-sanguineo-y-factor-rh", name: "GRUPO SANGUINEO Y FACTOR RH", category: "hematologia" },
  { id: "grupo-sanguineo-y-factor-rh-variante-du", name: "GRUPO SANGUINEO Y FACTOR RH VARIANTE DU", category: "hematologia" },
  { id: "h-de-crec-post-clonidin-60min", name: "H. DE CREC.(POST CLONIDIN) 60MIN", category: "hormonas" },
  { id: "h-de-crec-post-clonidin-90min", name: "H. DE CREC.(POST CLONIDIN) 90MIN", category: "hormonas" },
  { id: "h-de-crecimiento-120-min", name: "H. DE CRECIMIENTO 120 MIN", category: "hormonas" },
  { id: "h-de-crecimiento-15-min", name: "H. DE CRECIMIENTO 15 MIN", category: "hormonas" },
  { id: "h-de-crecimiento-180-min", name: "H. DE CRECIMIENTO 180 MIN", category: "hormonas" },
  { id: "h-de-crecimiento-30-min", name: "H. DE CRECIMIENTO 30 MIN", category: "hormonas" },
  { id: "h-de-crecimiento-45-min", name: "H. DE CRECIMIENTO 45 MIN", category: "hormonas" },
  { id: "h-de-crecimiento-60-min", name: "H. DE CRECIMIENTO 60 MIN", category: "hormonas" },
  { id: "h-de-crecimiento-90-min", name: "H. DE CRECIMIENTO 90 MIN", category: "hormonas" },
  { id: "h-de-crecimiento-basal", name: "H. DE CRECIMIENTO BASAL", category: "hormonas" },
  { id: "h-de-crecimiento-post-ejercicio", name: "H. DE CRECIMIENTO POST EJERCICIO", category: "hormonas" },
  { id: "h-de-crecimiento-post-clonidin", name: "H. DE CRECIMIENTO(POST CLONIDIN)", category: "hormonas" },
  { id: "helicobacter-pylori-igg", name: "HELICOBACTER PYLORI IGG", category: "anticuerpos" },
  { id: "helicobacter-pylori-igm", name: "HELICOBACTER PYLORI IGM", category: "anticuerpos" },
  { id: "hematies-recuento", name: "HEMATIES, RECUENTO", category: "hematologia" },
  { id: "hemocultivo", name: "HEMOCULTIVO", category: "cultivos" },
  { id: "hemocultivo-muestra-1", name: "HEMOCULTIVO MUESTRA 1", category: "cultivos" },
  { id: "hemocultivo-muestra-2", name: "HEMOCULTIVO MUESTRA 2", category: "cultivos" },
  { id: "hemocultivo-muestra-3", name: "HEMOCULTIVO MUESTRA 3", category: "cultivos" },
  { id: "hemocultivo-muestra-4", name: "HEMOCULTIVO MUESTRA 4", category: "cultivos" },
  { id: "hemocultivo-muestra-5", name: "HEMOCULTIVO MUESTRA 5", category: "cultivos" },
  { id: "hemocultivo-para-hongos", name: "HEMOCULTIVO PARA HONGOS", category: "parasitologia" },
  { id: "hemoglobina-hematocrito-hb-hto", name: "HEMOGLOBINA - HEMATOCRITO (HB, HTO)", category: "hematologia" },
  { id: "hemoglobina-glicosilada", name: "HEMOGLOBINA GLICOSILADA", category: "hematologia" },
  { id: "hemograma-automatizado", name: "HEMOGRAMA AUTOMATIZADO", category: "hematologia" },
  { id: "hep-a-ac-igm", name: "HEP. A AC. IGM", category: "anticuerpos" },
  { id: "hep-b-ag-de-superf-hbsag", name: "HEP. B AG. DE SUPERF.(HBsAg)", category: "infecciosas" },
  { id: "hep-b-antigeno-e", name: "HEP. B ANTIGENO E", category: "infecciosas" },
  { id: "hep-c-anticuerpos", name: "HEP. C, ANTICUERPOS", category: "anticuerpos" },
  { id: "hep-b-anti-ag-superficie-hbsab", name: "HEP.B ANTI.AG SUPERFICIE(HBSAB)", category: "infecciosas" },
  { id: "hep-b-core-total-hbcab", name: "HEP.B CORE TOTAL(HBCAB)", category: "infecciosas" },
  { id: "herpes-i-igg", name: "HERPES I IGG", category: "infecciosas" },
  { id: "herpes-i-igm", name: "HERPES I IGM", category: "infecciosas" },
  { id: "herpes-ii-igg", name: "HERPES II IGG", category: "infecciosas" },
  { id: "herpes-ii-igm", name: "HERPES II IGM", category: "infecciosas" },
  { id: "hidatidosis-ac-igg-echinococcus", name: "HIDATIDOSIS, AC IGG (ECHINOCOCCUS)", category: "anticuerpos" },
  { id: "hierro-serico", name: "HIERRO SERICO", category: "vitaminas" },
  { id: "hiv-i-y-ii-ag-p24", name: "HIV I Y II + AG P24", category: "infecciosas" },
  { id: "hormona-antimulleriana", name: "HORMONA ANTIMULLERIANA", category: "hormonas" },
  { id: "homocisteina-serica", name: "HOMOCISTEINA SERICA", category: "bioquimica" },
  { id: "htlv-1-2", name: "HTLV 1/2", category: "infecciosas" },
  { id: "indice-homa", name: "INDICE HOMA", category: "bioquimica" },
  { id: "influenza-a-b-prueba-rapida", name: "INFLUENZA A/B (PRUEBA RAPIDA)", category: "infecciosas" },
  { id: "inmunoglobulina-a", name: "INMUNOGLOBULINA A", category: "anticuerpos" },
  { id: "inmunoglobulina-e", name: "INMUNOGLOBULINA E", category: "anticuerpos" },
  { id: "inmunoglobulina-g", name: "INMUNOGLOBULINA G", category: "anticuerpos" },
  { id: "inmunoglobulina-m", name: "INMUNOGLOBULINA M", category: "anticuerpos" },
  { id: "inmunoglobulinas-inm-a-inm-g-inm-m", name: "INMUNOGLOBULINAS (INM. A, INM. G, INM. M)", category: "anticuerpos" },
  { id: "insulina", name: "INSULINA", category: "hormonas" },
  { id: "insulina-120-minutos", name: "INSULINA 120 MINUTOS", category: "hormonas" },
  { id: "insulina-150-minutos", name: "INSULINA 150 MINUTOS", category: "hormonas" },
  { id: "insulina-180-minutos", name: "INSULINA 180 MINUTOS", category: "hormonas" },
  { id: "insulina-30-minutos", name: "INSULINA 30 MINUTOS", category: "hormonas" },
  { id: "insulina-60-minutos", name: "INSULINA 60 MINUTOS", category: "hormonas" },
  { id: "insulina-90-minutos", name: "INSULINA 90 MINUTOS", category: "hormonas" },
  { id: "insulina-basal-y-post-prandial", name: "INSULINA BASAL Y POST PRANDIAL", category: "hormonas" },
  { id: "insulina-post-prandial", name: "INSULINA POST PRANDIAL", category: "hormonas" },
  { id: "inv-hongos-cuero-cabelludo", name: "INV.HONGOS.CUERO CABELLUDO", category: "parasitologia" },
  { id: "investig-de-hongos-de", name: "INVESTIG. DE HONGOS DE", category: "parasitologia" },
  { id: "investig-de-hongos-tobillo-derecho", name: "INVESTIG. DE HONGOS TOBILLO DERECHO", category: "parasitologia" },
  { id: "investig-de-parasitos", name: "INVESTIG. DE PARASITOS", category: "parasitologia" },
  { id: "investig-hongos-una-de-pie", name: "INVESTIG. HONGOS UÑA DE PIE", category: "parasitologia" },
  { id: "investig-pneumocystis-jirovecii-lav-bronquial", name: "INVESTIG. PNEUMOCYSTIS JIROVECII LAV. BRONQUIAL", category: "parasitologia" },
  { id: "investig-de-hongos-abdomen", name: "INVESTIG.DE HONGOS ABDOMEN", category: "parasitologia" },
  { id: "investig-hongos-antebrazo", name: "INVESTIG.HONGOS ANTEBRAZO", category: "parasitologia" },
  { id: "lactato-ca", name: "LACTATO (CA)", category: "bioquimica" },
  { id: "lactato-lcr", name: "LACTATO (LCR)", category: "liquidos" },
  { id: "lamina-periferica", name: "LAMINA PERIFERICA", category: "hematologia" },
  { id: "lh", name: "LH", category: "hormonas" },
  { id: "lh-post-estimulo", name: "LH POST ESTIMULO", category: "hormonas" },
  { id: "lipasa-en", name: "LIPASA EN", category: "bioquimica" },
  { id: "lipasa-serica", name: "LIPASA SERICA", category: "bioquimica" },
  { id: "lipidos-totales", name: "LIPIDOS TOTALES", category: "bioquimica" },
  { id: "lisis-euglobulinas", name: "LISIS EUGLOBULINAS", category: "coagulacion" },
  { id: "magnesio", name: "MAGNESIO", category: "vitaminas" },
  { id: "magnesio-orina-de-24-horas", name: "MAGNESIO (ORINA DE 24 HORAS)", category: "vitaminas" },
  { id: "magnesio-orina-al-azar", name: "MAGNESIO ORINA AL AZAR", category: "vitaminas" },
  { id: "marihuana-cualitativo-thc", name: "MARIHUANA CUALITATIVO(THC)", category: "toxicologia" },
  { id: "marihuana-cuantitativa", name: "MARIHUANA CUANTITATIVA", category: "toxicologia" },
  { id: "metadona-cualitativa", name: "METADONA CUALITATIVA", category: "toxicologia" },
  { id: "metanfetaminas-cualitativo", name: "METANFETAMINAS CUALITATIVO", category: "toxicologia" },
  { id: "microalbuminuria-en-orina-12hr", name: "MICROALBUMINURIA EN ORINA 12HR", category: "orina_heces" },
  { id: "microalbuminuria-en-orina-24hr", name: "MICROALBUMINURIA EN ORINA 24HR", category: "orina_heces" },
  { id: "microalbuminuria-orina-simple", name: "MICROALBUMINURIA ORINA SIMPLE", category: "orina_heces" },
  { id: "mitocondriales-autoanticuerpo", name: "MITOCONDRIALES, AUTOANTICUERPO", category: "anticuerpos" },
  { id: "monotest-paul-bunnell", name: "MONOTEST (PAUL BUNNELL)", category: "infecciosas" },
  { id: "morfina-cualitativo-opioides", name: "MORFINA CUALITATIVO (OPIOIDES)", category: "toxicologia" },
  { id: "morfologia-de-globulos-rojos-orina", name: "MORFOLOGIA DE GLOBULOS ROJOS(ORINA)", category: "orina_heces" },
  { id: "morfologia-globulos-rojos-sangre", name: "MORFOLOGIA GLOBULOS ROJOS (SANGRE)", category: "hematologia" },
  { id: "musculo-liso-anticuerpos-asma", name: "MUSCULO LISO, ANTICUERPOS (ASMA)", category: "anticuerpos" },
  { id: "nitrogeno-ureico-orina-simple", name: "NITROGENO UREICO ORINA SIMPLE", category: "orina_heces" },
  { id: "nitrogeno-ureico-plasmatico-bun", name: "NITROGENO UREICO PLASMATICO (BUN)", category: "bioquimica" },
  { id: "panel-gastrico-x-filmarray", name: "PANEL GASTRICO X FILMARRAY", category: "infecciosas" },
  { id: "panel-meningitis-x-filmarray-lcr", name: "PANEL MENINGITIS X FILMARRAY (LCR)", category: "infecciosas" },
  { id: "panel-pneumonico-x-filmarray", name: "PANEL PNEUMONICO X FILMARRAY", category: "infecciosas" },
  { id: "panel-respiratorio-x-filmarray", name: "PANEL RESPIRATORIO X FILMARRAY", category: "infecciosas" },
  { id: "perfil-ena-micro-array-ana-44-antigenos", name: "PERFIL ENA (MICRO ARRAY ANA 44 ANTIGENOS)", category: "perfiles" },
  { id: "parasitologico-concentrado", name: "PARASITOLOGICO CONCENTRADO", category: "parasitologia" },
  { id: "parasitologico-seriado-2-m", name: "PARASITOLOGICO SERIADO (2 M.)", category: "parasitologia" },
  { id: "parasitologico-seriado-3-m", name: "PARASITOLOGICO SERIADO (3 M.)", category: "parasitologia" },
  { id: "parasitologico-seriado-concentrado", name: "PARASITOLOGICO SERIADO CONCENTRADO", category: "parasitologia" },
  { id: "parasitologico-simple", name: "PARASITOLOGICO SIMPLE", category: "parasitologia" },
  { id: "parasitologico-simple-condic", name: "PARASITOLOGICO SIMPLE/CONDIC.", category: "parasitologia" },
  { id: "paratohormona", name: "PARATOHORMONA", category: "hormonas" },
  { id: "pcr-us-proteina-c-reactiva-ultrasensible", name: "PCR-US (PROTEINA C REACTIVA ULTRASENSIBLE)", category: "genetica" },
  { id: "peptido-c-120-min", name: "PEPTIDO C 120 MIN", category: "hormonas" },
  { id: "peptido-c-180-min", name: "PEPTIDO C 180 MIN", category: "hormonas" },
  { id: "peptido-c-60-min", name: "PEPTIDO C 60 MIN", category: "hormonas" },
  { id: "peptido-c-basal", name: "PEPTIDO C BASAL", category: "hormonas" },
  { id: "peptido-c-basal-y-post-prandial-peptido-c-peptido-pp", name: "PEPTIDO C BASAL Y POST PRANDIAL (PEPTIDO C, PEPTIDO PP)", category: "hormonas" },
  { id: "peptido-c-post-prandial", name: "PEPTIDO C POST PRANDIAL", category: "hormonas" },
  { id: "perfil-de-coagulacion-tp-inr-fibr-tpt-tc-ts", name: "PERFIL DE COAGULACION (TP, INR, FIBR, TPT, TC, TS)", category: "perfiles" },
  { id: "perfil-de-saturacion-de-transferrina-hierro-s-saturac-tranferr", name: "PERFIL DE SATURACION DE TRANSFERRINA (HIERRO S, %SATURAC, TRANFERR.)", category: "perfiles" },
  { id: "perfil-operatorio-li-hbsag-hiv-hbcab-hepc-htlv-1-2", name: "PERFIL OPERATORIO(LI) (HBSAG, HIV, HBCAB, HEPC, HTLV 1/2)", category: "perfiles" },
  { id: "perfil-femenino-testost-progest-prolac-lh-estrad-fsh-dhea-s", name: "PERFIL FEMENINO (TESTOST, PROGEST, PROLAC, LH, ESTRAD, FSH, DHEA-S)", category: "perfiles" },
  { id: "perfil-hemostatico-tp-tpt-inr-fibinogeno", name: "PERFIL HEMOSTATICO (TP, TPT, INR, FIBINOGENO)", category: "perfiles" },
  { id: "perfil-hepatico-con-ggtp-bil-dir-bil-ind-bil-tot-alb-fosfat-alc-glob-tgo-tgp-ggtp-prot-tot", name: "PERFIL HEPATICO CON GGTP (BIL.DIR, BIL. IND, BIL. TOT, ALB, FOSFAT.ALC, GLOB, TGO, TGP, GGTP, PROT.TOT)", category: "perfiles" },
  { id: "perfil-hepatico-sin-ggtp-bil-dir-bil-ind-bil-tot-alb-fosfat-alc-glob-tgo-tgp-prot-tot", name: "PERFIL HEPATICO SIN GGTP (BIL.DIR, BIL. IND, BIL. TOT, ALB, FOSFAT.ALC, GLOB, TGO, TGP, PROT.TOT)", category: "perfiles" },
  { id: "perfil-homa-ir-gluc-insul-homa-ir", name: "PERFIL HOMA IR (GLUC, INSUL, HOMA-IR)", category: "perfiles" },
  { id: "perfil-lipidico-r-coronario-col-tot-col-hdl-colt-ldl-col-vldl-trig-rel-ldl-hdl-rel-col-hdl", name: "PERFIL LIPIDICO/R.CORONARIO (COL.TOT, COL.HDL, COLT.LDL, COL.VLDL, TRIG, REL.LDL/HDL, REL.COL/HDL)", category: "perfiles" },
  { id: "perfil-prenatal-hma-gluc-creat-grupo-sang-eco-rpr", name: "PERFIL PRENATAL (HMA, GLUC, CREAT, GRUPO SANG, ECO, RPR)", category: "perfiles" },
  { id: "perfil-reticulocitos-rcto-absoluto", name: "PERFIL RETICULOCITOS (RCTO. ABSOLUTO)", category: "perfiles" },
  { id: "perfil-tiroideo-tsh-t4-lib-t3", name: "PERFIL TIROIDEO (TSH, T4 LIB, T3)", category: "perfiles" },
  { id: "perfil-torch-igg-toxo-igg-herp-ii-igg-rub-igg-citom-igg", name: "PERFIL TORCH IGG (TOXO.IGG, HERP.II IGG, RUB. IGG, CITOM. IGG)", category: "perfiles" },
  { id: "perfil-torch-igm-toxo-igm-herp-ii-igm-rub-igm-citom-igm", name: "PERFIL TORCH IGM (TOXO.IGM, HERP.II IGM, RUB. IGM, CITOM. IGM)", category: "perfiles" },
  { id: "ph-de", name: "PH DE", category: "bioquimica" },
  { id: "ph-en-sangre-venosa", name: "PH EN SANGRE VENOSA", category: "bioquimica" },
  { id: "plaquetas-recuento", name: "PLAQUETAS, RECUENTO", category: "hematologia" },
  { id: "plasma-citratado", name: "PLASMA CITRATADO", category: "bioquimica" },
  { id: "plasma-rico-en-plaquetas", name: "PLASMA RICO EN PLAQUETAS", category: "hematologia" },
  { id: "potasio-orina-simple", name: "POTASIO (ORINA SIMPLE)", category: "orina_heces" },
  { id: "potasio-orina-12-horas", name: "POTASIO ORINA 12 HORAS", category: "orina_heces" },
  { id: "potasio-orina-de-24-hrs", name: "POTASIO ORINA DE 24 HRS", category: "orina_heces" },
  { id: "potasio-serico", name: "POTASIO SERICO", category: "bioquimica" },
  { id: "pro-bnp", name: "PRO BNP", category: "bioquimica" },
  { id: "procalcitonina-pct-suero", name: "PROCALCITONINA (PCT)-(SUERO)", category: "bioquimica" },
  { id: "progesterona", name: "PROGESTERONA", category: "hormonas" },
  { id: "prolactina", name: "PROLACTINA", category: "hormonas" },
  { id: "prolactina-pm", name: "PROLACTINA PM", category: "hormonas" },
  { id: "prolactina-pool", name: "PROLACTINA POOL", category: "hormonas" },
  { id: "prot-t-y-f-liq-pleural-prot-tot-glob-alb", name: "PROT T Y F.  LIQ. PLEURAL (PROT.TOT, GLOB, ALB.)", category: "liquidos" },
  { id: "proteina-c-react-liq-pleural", name: "PROTEINA C REACT (LIQ.PLEURAL)", category: "liquidos" },
  { id: "proteina-c-reactiva", name: "PROTEINA C REACTIVA", category: "anticuerpos" },
  { id: "proteinas-lcr", name: "PROTEINAS (LCR)", category: "liquidos" },
  { id: "proteinas-liq-sinovial", name: "PROTEINAS (LIQ. SINOVIAL)", category: "liquidos" },
  { id: "proteinas-al-azar", name: "PROTEINAS AL AZAR", category: "bioquimica" },
  { id: "proteinas-de-bences-jones-o24h", name: "PROTEINAS DE BENCES JONES (O24H)", category: "bioquimica" },
  { id: "proteinas-liq-ascitico", name: "PROTEINAS LIQ. ASCITICO", category: "liquidos" },
  { id: "proteinas-liq-pleural", name: "PROTEINAS LIQ. PLEURAL", category: "liquidos" },
  { id: "proteinas-totales-y-fraccion-alb-glob-prot-tot", name: "PROTEINAS TOTALES Y FRACCION. (ALB., GLOB, PROT.TOT)", category: "bioquimica" },
  { id: "proteinuria-cualitativa", name: "PROTEINURIA CUALITATIVA", category: "bioquimica" },
  { id: "proteinuria-de-12-horas", name: "PROTEINURIA DE 12 HORAS", category: "bioquimica" },
  { id: "proteinuria-en-orina-al-azar", name: "PROTEINURIA EN ORINA AL AZAR", category: "orina_heces" },
  { id: "proteinuria-orina-de-24-hrs", name: "PROTEINURIA ORINA DE 24 HRS", category: "orina_heces" },
  { id: "prueba-antigeno-covid-sec-nasal", name: "PRUEBA ANTIGENO COVID SEC.NASAL", category: "genetica" },
  { id: "psa-libre", name: "PSA LIBRE", category: "marcadores" },
  { id: "psa-perfil-psa-tot-psa-lib-psa-index", name: "PSA PERFIL (PSA TOT, PSA LIB, PSA INDEX)", category: "perfiles" },
  { id: "psa-antigeno-prostatico-especifico", name: "PSA(ANTIGENO/PROSTATICO/ESPECIFICO)", category: "marcadores" },
  { id: "quantiferon-igra", name: "QUANTIFERON - (IGRA)", category: "infecciosas" },
  { id: "rcto-de-leucocitos-semen", name: "RCTO DE LEUCOCITOS(SEMEN)", category: "fertilidad" },
  { id: "reaccion-de-widal-aglutinaciones", name: "REACCION DE WIDAL(AGLUTINACIONES)", category: "infecciosas" },
  { id: "reaccion-inflamatoria-en-heces", name: "REACCION INFLAMATORIA EN HECES", category: "orina_heces" },
  { id: "recuento-de-leucocit-heces", name: "RECUENTO DE LEUCOCIT.(HECES)", category: "orina_heces" },
  { id: "relacion-albumina-creatinina-en-orina", name: "RELACION ALBUMINA/CREATININA EN ORINA", category: "orina_heces" },
  { id: "reticulocitos", name: "RETICULOCITOS", category: "hematologia" },
  { id: "retraccion-del-coagulo", name: "RETRACCION DEL COAGULO", category: "coagulacion" },
  { id: "rotavirus", name: "ROTAVIRUS", category: "infecciosas" },
  { id: "rotavirus-y-adenovirus", name: "ROTAVIRUS Y ADENOVIRUS", category: "infecciosas" },
  { id: "rpr-serologias-vdrl", name: "RPR (SEROLOGIAS)VDRL", category: "infecciosas" },
  { id: "rpr-cuantitativo", name: "RPR CUANTITATIVO", category: "infecciosas" },
  { id: "rpr-en-lcr", name: "RPR EN LCR", category: "infecciosas" },
  { id: "rubeola-igg", name: "RUBEOLA IGG", category: "infecciosas" },
  { id: "rubeola-igm", name: "RUBEOLA IGM", category: "infecciosas" },
  { id: "sangre-oculta-inmunologico-seriado-2-muestras", name: "SANGRE OCULTA (INMUNOLOGICO)SERIADO 2 MUESTRAS", category: "orina_heces" },
  { id: "sangre-oculta-inmunologico-seriado-3-muestras", name: "SANGRE OCULTA (INMUNOLOGICO)SERIADO 3 MUESTRAS", category: "orina_heces" },
  { id: "sangre-oculta-en-heces", name: "SANGRE OCULTA EN HECES", category: "orina_heces" },
  { id: "sangre-oculta-en-heces-inmunologico", name: "SANGRE OCULTA EN HECES(INMUNOLOGICO)", category: "orina_heces" },
  { id: "sangria", name: "SANGRIA", category: "coagulacion" },
  { id: "sodio-orina-simple", name: "SODIO (ORINA SIMPLE)", category: "orina_heces" },
  { id: "sodio-orina-de-12-horas", name: "SODIO ORINA DE 12 HORAS", category: "orina_heces" },
  { id: "sodio-orina-de-24-horas", name: "SODIO ORINA DE 24 HORAS", category: "orina_heces" },
  { id: "sodio-sangre", name: "SODIO SANGRE", category: "bioquimica" },
  { id: "somatomedina-post-clonidina-suero", name: "SOMATOMEDINA (POST CLONIDINA)-(SUERO)", category: "hormonas" },
  { id: "somatomedina-post-ejercicio-suero", name: "SOMATOMEDINA (POST EJERCICIO)-(SUERO)", category: "hormonas" },
  { id: "somatomedina-c-igf-1", name: "SOMATOMEDINA C (IGF-1)", category: "hormonas" },
  { id: "sudan-iii", name: "SUDAN III", category: "bioquimica" },
  { id: "sustancias-reductoras-benedict", name: "SUSTANCIAS REDUCTORAS (BENEDICT)", category: "bioquimica" },
  { id: "t-g-o-transaminasa-oxalacetica", name: "T.G.O (TRANSAMINASA OXALACETICA)", category: "bioquimica" },
  { id: "t-g-p-transaminasa-piruvica", name: "T.G.P (TRANSAMINASA PIRUVICA)", category: "bioquimica" },
  { id: "t3", name: "T3", category: "hormonas" },
  { id: "t3-libre", name: "T3 LIBRE", category: "hormonas" },
  { id: "t4", name: "T4", category: "hormonas" },
  { id: "t4-libre", name: "T4 LIBRE", category: "hormonas" },
  { id: "tasa-de-filtracion-glomerular-gfr-ckd-epi", name: "TASA DE FILTRACION GLOMERULAR-GFR (CKD-EPI)", category: "bioquimica" },
  { id: "tehevenon", name: "TEHEVENON", category: "bioquimica" },
  { id: "test-de-alergia-alex2", name: "TEST DE ALERGIA ALEX2", category: "alergias" },
  { id: "test-de-aliento", name: "TEST DE ALIENTO", category: "bioquimica" },
  { id: "test-de-coombs-directo", name: "TEST DE COOMBS DIRECTO", category: "hematologia" },
  { id: "test-de-coombs-indirecto", name: "TEST DE COOMBS INDIRECTO", category: "hematologia" },
  { id: "test-de-graham", name: "TEST DE GRAHAM", category: "parasitologia" },
  { id: "test-de-graham-2-muestras", name: "TEST DE GRAHAM (2 MUESTRAS)", category: "parasitologia" },
  { id: "test-de-graham-seriado-graham-1-graham-2-graham-3", name: "TEST DE GRAHAM SERIADO (GRAHAM 1, GRAHAM 2, GRAHAM 3)", category: "parasitologia" },
  { id: "test-de-sullivan", name: "TEST DE SULLIVAN", category: "bioquimica" },
  { id: "testosterona", name: "TESTOSTERONA", category: "hormonas" },
  { id: "testosterona-libre", name: "TESTOSTERONA LIBRE", category: "hormonas" },
  { id: "testosterona-post-hcg", name: "TESTOSTERONA POST HCG", category: "hormonas" },
  { id: "thevenon", name: "THEVENON ()", category: "bioquimica" },
  { id: "tiempo-de-coagulacion-y-sangria-tc-ts", name: "TIEMPO DE COAGULACION Y SANGRIA (TC, TS)", category: "coagulacion" },
  { id: "tiempo-de-protrombina-tp-tpt-inr", name: "TIEMPO DE PROTROMBINA (TP, %TPT, INR)", category: "coagulacion" },
  { id: "tiempo-de-trombina", name: "TIEMPO DE TROMBINA", category: "coagulacion" },
  { id: "tiempo-parcial-tromboplastina-activado", name: "TIEMPO PARCIAL TROMBOPLASTINA ACTIVADO", category: "bioquimica" },
  { id: "tinta-china-de", name: "TINTA CHINA DE", category: "parasitologia" },
  { id: "tinta-china-en-lcr", name: "TINTA CHINA EN LCR", category: "parasitologia" },
  { id: "tiroglobulina-en", name: "TIROGLOBULINA EN", category: "hormonas" },
  { id: "tiroglobulina-ganglio-cervical", name: "TIROGLOBULINA GANGLIO CERVICAL", category: "hormonas" },
  { id: "tiroglobulina-serica", name: "TIROGLOBULINA SERICA", category: "hormonas" },
  { id: "tolerancia-a-la-glucosa-2-horas", name: "TOLERANCIA A LA GLUCOSA 2 HORAS", category: "bioquimica" },
  { id: "tolerancia-a-la-glucosa-3-horas", name: "TOLERANCIA A LA GLUCOSA 3 HORAS", category: "bioquimica" },
  { id: "tolerancia-a-la-insulina-3-tomas", name: "TOLERANCIA A LA INSULINA (3 TOMAS)", category: "hormonas" },
  { id: "tolerancia-a-la-insulina-7-tomas", name: "TOLERANCIA A LA INSULINA (7 TOMAS)", category: "hormonas" },
  { id: "tolerancia-a-la-insulina-2-horas", name: "TOLERANCIA A LA INSULINA 2 HORAS", category: "hormonas" },
  { id: "toxoplasma-gondii-igg", name: "TOXOPLASMA GONDII IGG", category: "infecciosas" },
  { id: "toxoplasma-gondii-igm", name: "TOXOPLASMA GONDII IGM", category: "infecciosas" },
  { id: "tpt-corregido-con-plasma-normal", name: "TPT CORREGIDO CON PLASMA NORMAL", category: "coagulacion" },
  { id: "transferrina", name: "TRANSFERRINA", category: "vitaminas" },
  { id: "tricograma-de-cabello", name: "TRICOGRAMA DE CABELLO", category: "parasitologia" },
  { id: "tricograma-de-cejas", name: "TRICOGRAMA DE CEJAS", category: "parasitologia" },
  { id: "trigliceridos", name: "TRIGLICERIDOS", category: "bioquimica" },
  { id: "trigliceridos-en-liquido-ascitico", name: "TRIGLICERIDOS  EN LIQUIDO ASCITICO", category: "liquidos" },
  { id: "trigliceridos-en-liq-pleural", name: "TRIGLICERIDOS EN LIQ. PLEURAL", category: "liquidos" },
  { id: "tripanosoma-cruzi-chagas", name: "TRIPANOSOMA-CRUZI (CHAGAS)", category: "infecciosas" },
  { id: "troponina-t-stat", name: "TROPONINA T STAT", category: "bioquimica" },
  { id: "tsh", name: "TSH", category: "hormonas" },
  { id: "tsh-ganglio-cervical", name: "TSH GANGLIO CERVICAL", category: "hormonas" },
  { id: "urea-de", name: "UREA DE", category: "bioquimica" },
  { id: "urea-en-orina-12-hrs", name: "UREA EN ORINA 12 HRS.", category: "orina_heces" },
  { id: "urea-en-orina-24-hrs", name: "UREA EN ORINA 24 HRS.", category: "orina_heces" },
  { id: "urea-orina-al-azar", name: "UREA ORINA AL AZAR", category: "orina_heces" },
  { id: "urea-post-dialisis", name: "UREA POST DIALISIS", category: "bioquimica" },
  { id: "urea-predialisis", name: "UREA PREDIALISIS", category: "bioquimica" },
  { id: "urea-serica", name: "UREA SERICA", category: "bioquimica" },
  { id: "urocultivo", name: "UROCULTIVO", category: "cultivos" },
  { id: "uroporfirina-orina-24h", name: "UROPORFIRINA (orina 24h)", category: "orina_heces" },
  { id: "velocidad-de-sediment-vsg", name: "VELOCIDAD DE SEDIMENT. (VSG)", category: "hematologia" },
  { id: "velocidad-de-sedimentacion-2-horas", name: "VELOCIDAD DE SEDIMENTACION (2 HORAS)", category: "hematologia" },
  { id: "vitamina-b12", name: "VITAMINA B12", category: "vitaminas" },
  { id: "vitamina-d-25-hidroxi", name: "VITAMINA D (25 HIDROXI)", category: "vitaminas" },
];